apiVersion: v1
kind: Service
metadata:
  name: learningsteps-api
  namespace: production
  labels:
    app: learningsteps-api
spec:
  type: LoadBalancer
  selector:
    app: learningsteps-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
